name: reviewdog

on:
  pull_request:
    branches: [ master ]

jobs:
  reviewdog-github-check:
    name: reviewdog (github-check)
    runs-on: ubuntu-latest

    steps:
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - uses: actions/checkout@v2

      - name: Install node_modules
        run: npm install
      
      - name: Execute textlint
        run: npx textlint -f checkstyle "content/*.md" >> .textlint.log

      - name: Run reviewdog
        # textlintで文章上のミスがあった場合のみ、reviewdogを実行させるようにする
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat .textlint.log | reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
